### ISSUE TITLE
Support multiple metrics in one query

### ISSUE THREAD

**Issue by itomaldonado** [JamesOsgood/mongodb-grafana#10]
I was trying to support multiple data (metrics) in a single query, but I saw the code doesn't support it right now.

Here is an example:

Data:
```
{"_id": <some id>, "type": "type1", "ts": someTS}
{"_id": <some id>, "type": "type1", "ts": someTS}
{"_id": <some id>, "type": "type2", "ts": someTS}
{"_id": <some id>, "type": "type3", "ts": someTS}
```

You do an aggregation grouping on both TS *and* the type and count them:
```
{"$group":{"_id":{"type":"$type","ts":"$ts"}},"count":{"$sum":1.0}}}
```

And finally you use the project:

```
{"$project":{"name":"$_id.type","value":"$count","ts":"$_id.ts"}}
```

Mongo will return something like:
```
[
  {  "name": "type1",
      "ts": someTS,
      "value": 2
  },
  {  "name": "type2",
      "ts": someTS,
      "value": 1
  },
  {  "name": "type3",
      "ts": someTS,
      "value": 1
  }
]
```

So the server should parse this and respond with data like:

```
...
"response": [
  {  "target": "type1",
      "datapoints": [ [2,someTS] ]
  },
  {  "target": "type2",
      "datapoints": [ [1,someTS] ]
  },
  {  "target": "type3",
      "datapoints": [ [1,someTS] ]
  },
]
```

This will force Grafana to have a metric line *per* target, which is great for these types of aggregation (e.g. count students per schools per state, count of purchases per person per store etc...)

I have some changes that can be done to do this, if you want I can go ahead and implement them and raise a PR?

**Comment by JamesOsgood** [comment]
Sure, go ahead!

I only really implemented enough to get my raspberry pi graphs working....

James

**Comment by deebee07** [comment]
So currently what I see is it doesnt support for tabular data type ? Correct me if I an wrong here !!

**Comment by minh0722** [comment]
Any update on this? I managed to change the code a bit so the response is like what you said but it's not displaying and there is some error on grafana side "cannot read property toString of undefined"

**Comment by JamesOsgood** [comment]
I have just pushed an update that supports Table Panels

**Comment by hanangger** [comment]
does this also support for timeseries?

**Comment by JamesOsgood** [comment]
Yes, both.

**Comment by hanangger** [comment]
Sorry, Does this also support for Graph panel timeseries?

**Comment by JamesOsgood** [comment]
Yes, please see
https://github.com/JamesOsgood/mongodb-grafana/blob/master/README.md for
examples

**Comment by hanangger** [comment]
But, the case it that I want to count row as value each timeline 

here is my script

`db.event_input.aggregate( [ 
{  "$match" :  {  "ts" : { "$gte" : "$from", "$lt" : "$to" }}},
{ "$group" : { "_id" : { "type" : "$type", "ts" : "$ts" }, "count" : { "$sum" : 1.0 }  } },
{"$project":{"name":"$_id.type", "value":"$count","ts":"$_id.ts"}}  ]  )`

and I want to apply in Graph panel in timeseries

**Comment by JamesOsgood** [comment]
Yep, that works,

[image: Screen Shot 2018-08-08 at 16.12.11.png]
