### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Adhira-Deogade** [JamesOsgood/mongodb-grafana#112]
I am facing same issues - my query is this -
db.test_profile.aggregate ( [ { "$match" : { "job_name" : "metric_name", "start_time" : { "$gte" : "15" } } } ])

and response is -
response:Array[0]

**Comment by JamesOsgood** [comment]
You need to project out the fields the plugin is expecting

{"$project": {"name" : "test", "value" : "$Value", "ts" : "$Timestamp",
"_id" : 0 } } ])

The API is expecting back documents with the following fields

   - name - Name of the series ( will be displayed on the graph)
   - value - The float value of the point
   - ts - The time of the point as a BSON date

These documents are then converted into the Grafana API
<http://docs.grafana.org/plugins/developing/datasources/>


James

**Comment by Adhira-Deogade** [comment]
It worked!
Thank you so so much, @JamesOsgood

**Comment by Adhira-Deogade** [comment]
I kept the time key as epoch time, this was the issue. I am using pymongo and now I used datetime to get it working. In case anyone stumbles on similar issue.

**Comment by oyearunpal** [comment]
You can also use your query as below
```
db.test_profile.aggregate([
{"$match":{"job_name" : "metric_name"} }
])
```
But you have to change "timeseries" to "table"
