### ISSUE TITLE
How to add add alias on these queries currently I get it as undefined 

### ISSUE THREAD

**Issue by Tibingeo** [JamesOsgood/mongodb-grafana#16]
<img width="199" alt="screen shot 2018-07-19 at 4 17 43 pm" src="https://user-images.githubusercontent.com/16147643/42938292-67bb938c-8b6f-11e8-9745-d39a2dc68b86.png">

**Comment by JamesOsgood** [comment]
Project a 'name' field - like {  "$project" :  {  "name" : "Enviro pHAT",  "value" : "$maxValue",  "ts" : "$_id.min",  "_id" : 0  }  }  ]  )

**Comment by Tibingeo** [comment]
Thank You @JamesOsgood
