### ISSUE TITLE
Cannot fetch data 

### ISSUE THREAD

**Issue by yulidai** [JamesOsgood/mongodb-grafana#19]
Query:
db.test.aggregate([{$group : {_id : "$name”, num_tutorial : {$sum : 1}}}])

Error in Response:
{ "message": "Unexpected token $ in JSON at position 3" }

I'm a novice at these things, can you help me what wrong with it?

**Comment by JamesOsgood** [comment]
You need to enclose $group and $sum in quotes.

**Comment by yulidai** [comment]
Query:
db.test.aggregate()

Error in Response
{ "message": "Cannot read property 'length' of undefined" }

**Comment by yulidai** [comment]
Thanks for your reply. I changed query to:
db.test.aggregate({"$group" : {"_id" : "$name", "num_tutorial" : {"$sum" : 1}}})

Then there's no wrong messge.  But still not info showed in "Table Panel", but has result when running in mongo-cli

**Comment by minh0722** [comment]
you need to project the following fields in order for it to show on the panel:
```
db.test.aggregate([
    {"$group" : {
        "_id" : "$name",
        "num_tutorial" : {"$sum" : 1},
        "time" : {"$first" : "$your_time_column_name"}
    }},
    {"$project" : {
        "name" : "$_id",
        "value" : "$num_tutorial",
        "ts" : "$time",
        "_id" : 0
    }}
])
```

You can check the README for more info on the required fields that the api expects

**Comment by yulidai** [comment]
@minh0722 Thank you for your patience

Here is my data in mongo with command in mongo: 
> db.myCollection.find()
```
{ "_id" : ObjectId("5b6c2f134202c48ce09a6a13"), "time" : 1533816595792, "value" : 1, "metric" : "first" }
{ "_id" : ObjectId("5b6c2f1b4202c48ce09a6a14"), "time" : 1533816603521, "value" : 3, "metric" : "second" }
{ "_id" : ObjectId("5b6c34a74202c48ce09a6a15"), "time" : 1533818023968, "value" : 5, "metric" : "second" }
```

**Then the query in panel is:**
```
db.myCollection.aggregate([
    {"$group" : {
        "_id" : "$name",
        "num_tutorial" : {"$sum" : 1},
        "time" : {"$first" : "$time"}
    }},
    {"$project" : {
        "name" : "$_id",
        "value" : "$num_tutorial",
        "ts" : "$time",
        "_id" : 0
    }}
])
```
But still nothing showed in either Graph or Table. Any help will be appreciated, thank you!

**Comment by minh0722** [comment]
You don't have a column `name` anywhere in your db. Try changing `"_id" : "$name"` to `"_id" : "$_id"`

**Comment by yulidai** [comment]
@minh0722 Thank you for your patience!

Here is my data in mongo with command:
> db.myCollection.find()
```
{ "_id" : ObjectId("5b6c2f134202c48ce09a6a13"), "time" : 1533816595792, "value" : 1, "metric" : "first" }
{ "_id" : ObjectId("5b6c2f1b4202c48ce09a6a14"), "time" : 1533816603521, "value" : 3, "metric" : "second" }
{ "_id" : ObjectId("5b6c34a74202c48ce09a6a15"), "time" : 1533818023968, "value" : 5, "metric" : "second" }
```

**Then the query in panel is:**
```
db.myCollection.aggregate([
    {"$group" : {
        "_id" : "$_id",
        "num_tutorial" : {"$sum" : 1},
        "time" : {"$first" : "$time"}
    }},
    {"$project" : {
        "name" : "$_id",
        "value" : "$num_tutorial",
        "ts" : "$time",
        "_id" : 0
    }}
])
```

But still nothing showed in either Graph or Table. Any help will be appreciated, thank you!

**Comment by minh0722** [comment]
Sorry I edited my prev comment

**Comment by yulidai** [comment]
@minh0722 Thank you, Still nothing after changing, any other problem?

**Comment by minh0722** [comment]
what's the response from the query?

**Comment by yulidai** [comment]
target is
```
target:"db.myCollection.aggregate([ {"$group" : { "_id" : "$metric", "num_tutorial" : {"$sum" : 1}, "time" : {"$first" : "$time"} }}, {"$project" : { "name" : "$_id", "value" : "$num_tutorial", "ts" : "$time", "_id" : 0 }} ])"
```
response is
```
response:Array[1]
    0:Object
        columns:Array[0]
        rows:Array[0]
    type:"table"
```

**Comment by minh0722** [comment]
change the type to timeserie. Table type is not supported

**Comment by yulidai** [comment]
Result after changing type to timeserie 
```
response:Array[0]
```

**Comment by yulidai** [comment]
Maybe the reason is caused by time zone(here is china), but when i change time range from "last 6h" to "last 24h". But still nothing to show, i don't know why... T.T

**Comment by minh0722** [comment]
I dont think that's the problem cause you dont have a "$match" pipeline in your aggregate. But just to try it out add this before "$group":
{ "$match" :    { "time" : { "$gte" : "$from", "$lte" : "$to" } }  },

**Comment by minh0722** [comment]
did you select the datasource that is above the query box?

**Comment by yulidai** [comment]
Here is the db config: 
```
db:Object
  url:"mongodb://rpiread:rpiread@rpi-sensor-data-shard-00-00-ifxxs.mongodb.net:27017,rpi-sensor-data-shard-00-01-ifxxs.mongodb.net:27017,rpi-sensor-data-shard-00-02-ifxxs.mongodb.net:27017/test?ssl=true&replicaSet=rpi-sensor-data-shard-0&authSource=admin"
  db:"test"
```

And the mongodb is running in local, Datasource testing info is:
> Data source is working

**Comment by yulidai** [comment]
Yes i did select the mongodb as the datasouce

**Comment by yulidai** [comment]
Oh my god, the Datasource testing always success even though closing the database. I think is the proxy hide the error, i'll check it...

**Comment by minh0722** [comment]
check if data source is correctly configured. I had problem with some proxy settings and I had to write the full proxy domain name in mongodb url so you can check that too

**Comment by yulidai** [comment]
@minh0722 When i change "MongoDB URL" to localhost, the response is different:
target:
```
db.myCollection.aggregate([ {
  "$group" : { 
    "_id" : "$metric",
    "num_tutorial" : {"$sum" : 1},
    "time" : {"$first" : "$time"} }
}, {
  "$project" : { 
    "name" : "$_id", 
    "value" : "$num_tutorial", 
    "ts" : "$time", "_id" : 0 }
} ])
```
response:
```
response:Object
  message:"doc.ts.getTime is not a function"
```

**Comment by minh0722** [comment]
I think the field time has to be of type Date

**Comment by yulidai** [comment]
Right, it's ok after changing the type of time, thanks!

**Comment by jonymaldo** [comment]
> 
> 
> Right, it's ok after changing the type of time, thanks!


@yulidai How was this problem solved? I have the same problem, I changed the time type to isodate but it doesn't work.

**Comment by Adhira-Deogade** [comment]
I am facing same issues - my query is this - 
db.test_profile.aggregate ( [ { "$match" : { "job_name" : "metric_name",  "start_time" : { "$gte" : "15" } } } ])

and response is - 
response:Array[0]
