### ISSUE TITLE
Error while importing dashboard

### ISSUE THREAD

**Issue by FluffyAlpaca** [JamesOsgood/mongodb-grafana#3]
Hi! 
First of all, thank you for your plugin! 
I'm on Windows and I installed it in the plugin folder, as you describe in your installation guideline. I installed npm and node too and launched the server. 
So the installation went fine, I can choose "MongoDB" in the datasource type. Then, after creating the "RPI-Atlas" datasource as described in your tutorial, I tried to import the dashboard you provide in the "examples" folder. But I get an "Internal Server Error", with the following response details : 

`&#10;&#10;&#10;&#10;Error&#10;&#10;&#10;<pre>SyntaxError: Unexpected end of JSON input<br> &#160; &#160;at JSON.parse (&lt;anonymous&gt;)<br> &#160; &#160;at parseQuery (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\dist\server\mongodb-proxy.js:213:29)<br> &#160; &#160;at C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\dist\server\mongodb-proxy.js:116:19<br> &#160; &#160;at Layer.handle [as handle_request] (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\layer.js:95:5)<br> &#160; &#160;at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:137:13)<br> &#160; &#160;at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)<br> &#160; &#160;at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)<br> &#160; &#160;at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)<br> &#160; &#160;at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)<br> &#160; &#160;at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)</pre>&#10;&#10;&#10;`

Would you have any idea where the error comes from ?

**Comment by JamesOsgood** [comment]
Hi,

This is the server trying to connect to Mongo. It looks like there is a bug in the server when a substitution parameter has a '.' in it.

Try changing the 'host' dropdown to 'rp1'.

Alternatively, editing the config/default.json to enable logging, then restarting the node server should log stuff to mongodb-proxy.log.

James

**Comment by FluffyAlpaca** [comment]
Hi, 

Thank you for your answer. Changing the host didn't do anything, the dropdown was empty and when I put it by hand, the error stayed the same.
However,  I noticed, in the logs of the terminal where I ran "npm run server", that line : 

`MongoNetworkError: failed to connect to server [rpi-sensorreadings-shard-00-02-fgscn.mongodb.net:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 18.195.106.174:27017]`

so I think it must be the firewall. 
I'm going to test the plugin with a VM on my computer so I won't have to allow the port on the firewall. 

I'll tell you if I have the same issue!

**Comment by FluffyAlpaca** [comment]
Okay so the issue is gone, now I have another error: 

`TypeError: Cannot read property 'getTime' of undefined`

Do you have an idea about it?

**Comment by JamesOsgood** [comment]
Can you add a screenshot of your grafana window and also provide the full
error?

Jamew

**Comment by FluffyAlpaca** [comment]
Yes of course:
![image](https://user-images.githubusercontent.com/25431347/38677407-7f2f6894-3e5e-11e8-90f9-d85cc70d2d14.png)
![image](https://user-images.githubusercontent.com/25431347/38677454-9f6c5400-3e5e-11e8-9480-8c5e3a33b606.png)
![image](https://user-images.githubusercontent.com/25431347/38677506-c062484a-3e5e-11e8-8a49-c263ccf3d7c7.png)
![image](https://user-images.githubusercontent.com/25431347/38677521-cba0b444-3e5e-11e8-8ee5-7aafe3c1d571.png)

And the full error:
`TypeError: Cannot read property 'getTime' of undefined
    at C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\dist\server\mongodb-proxy.js:281:58
    at args.push (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\utils.js:404:72)
    at handleCallback (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\utils.js:128:55)
    at self.close (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\cursor.js:934:60)
    at handleCallback (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\utils.js:128:55)
    at completeClose (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\cursor.js:1073:14)
    at AggregationCursor.Cursor.close (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\cursor.js:1086:10)
    at C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb\lib\cursor.js:934:21
    at handleCallback (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb-core\lib\cursor.js:178:5)
    at setCursorDeadAndNotified (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\mongodb-core\lib\cursor.js:545:3)`

I used this database from the tutorial MongoDB:
https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json
and tested the query in MongoShell before passing it into Graphana.

**Comment by FluffyAlpaca** [comment]
I tried with this query : 

`db.restaurants.aggregate ( [ 
{ "$match" :    {   "borough" : "Queens",   "cuisine" : "Chinese", "date" : { "$gte" : "1325372400000", "$lt" : "1523536649740" } }  },        
 {"$sort" : {"name" : 1}}            
  ])`

I don't have the error anymore, but my panel is still empty.

**Comment by FluffyAlpaca** [comment]
Okay, it was my fault, my query was wrong. I found a way to query a date into my database with this query : 
db.restaurants.aggregate ( 

> [ 
> { "$match" :    {   "borough" : "Queens",   "cuisine" : "Chinese", "grades.date" : { "$gte" :  "ISODate('2012-02-12T00:00:00Z')", "$lt" : "ISODate('2018-02-12T00:00:00Z')" } }  },        
>  {"$sort" : {"name" : 1}}            
>   ])

But now the error is : 
`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseQuery (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\dist\server\mongodb-proxy.js:213:29)
    at C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\dist\server\mongodb-proxy.js:116:19
    at Layer.handle [as handle_request] (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:137:13)
    at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\mmilhau\Documents\Grafana\grafana-5.0.4\data\plugins\mongodb-grafana\node_modules\express\lib\router\route.js:131:14)`

**Comment by JamesOsgood** [comment]
Hi,

See the comments in the md file

The API is expecting back documents with the following fields

name - Name of the series ( will be displayed on the graph)
value - The float value of the point
ts - The time of the point as a BSON date
These documents are then converted into the Grafana API

You need a $project stage to project those values like in the example. The server side js is looking for those fields.

db.sensor_value.aggregate( [ 
{  "$match" :  {  "sensor_type" : "$sensor", "host_name" : "$host" , "ts" : { "$gte" : "$from", "$lt" : "$to" }}},
{  "$bucketAuto" :  { "groupBy" : "$ts",  
                           "buckets" : "$dateBucketCount", 
                            "output" :  {  "maxValue" : { "$max" : "$sensor_value" }  }   }   },  
{  "$project" :  {  "name" : "value",  "value" : "$maxValue",  "ts" : "$_id.min",  "_id" : 0  }  }  ]  )

**Comment by FluffyAlpaca** [comment]
Thank you for your help, I'm trying to correct my query. Will this work on table panel too? Or is it working only on graph panels?

I don't quite understand what the "value" field is corresponding to... Is this the Y axis? And the "ts" field would be the X axis?

**Comment by FluffyAlpaca** [comment]
Hi! I made it work, thank you again for your help! I confirm, it also works on table panels. 
Sorry for all the questions, I'm new to Graphana and MongoDB.
I put my query here, juste in case it could help somebody else. I used the example dataset from the MongoDB documentation (https://docs.mongodb.com/getting-started/shell/import-data/). 


```
db.restaurants.aggregate( [ 
{"$match": {"borough": "Queens", "cuisine": "Chinese", "grades.date":{"$gte": "$from", "$lt": "$to" }} },  
{"$sort":{"name": 1}}, 
{ "$project" : { "name" : "table", "value" : { "$arrayElemAt": ["$grades.score", 0]}, "ts" : { "$arrayElemAt": ["$grades.date", 0]}, "_id" : 0 } } 
] )
```

I'm closing the issue now, have a nice day!
