### ISSUE TITLE
How to use series for x-axis ?

### ISSUE THREAD

**Issue by yinsimei** [JamesOsgood/mongodb-grafana#36]
Hello, I'm trying to use another value for x-axis than time series, so I try to choose "Series" for X-Axis in the Axis tab, but I'm not sure what the name of variable for me to assign the x values.

This is the example for my Query, do you have an idea for the **"variableDontKnowNameForXAxis"** below?

db.analytic_events.aggregate([
{
	"$match": {
		"event_time": { "$gte": "$from", "$lte": "$to" },
		"event_type": "CampBakingStats_1.0"
	}
},
{
	"$project": {
		"ts": "$event_time",
                 **"variableDontKnowNameForXAxis" : "$custom_payload.codeCL"**
		"name": "$custom_payload.codeCL",
		"value": "$custom_payload.campTotalDuration"
	}
},
{
	"$sort": { "ts": 1 }
}
])

**Comment by yinsimei** [comment]
Hi, I also notice that you've added the support for 'table' in a previous commit but it seems that my queries are always executed via "getTimeseriesResults" and never fall into "getTableResult".

I guess there may be sth that I miss to make it work properly?

**Comment by JamesOsgood** [comment]
Hi,

You need to change the dropdown in Grafana when defining the query from
'timeserie' to 'table'

James

**Comment by yinsimei** [comment]
Thanks a lot for your reply. I tried to choose 'table' for the query drop down and use 'series' for the graph.

The graph I get shows only the last result. Do I still miss something here?
![image](https://user-images.githubusercontent.com/12700377/50909679-a02e0d80-142c-11e9-9880-a67d0026cbbc.png)

Here is my query:
db.analytic_events.aggregate([
    {"$match": {
        "event_time": { "$gte": "$from", "$lte": "$to" },
        "event_type": "CampBakingStats_1.0"
    }},
    {"$group": {
        "_id": { "changelist" : "$custom_payload.codeCL" },
        "campBakingTotalDuration" : {"$sum": "$custom_payload.campBakingTotalDuration" },
        "max_event_time": { "$max": "$event_time" }
    }},
    {"$project": {
        "name" : "$_id.changelist",
        "value" : "$campBakingTotalDuration",
        "ts" : "$max_event_time",
        "_id": 0
    }},
    {"$sort":
        { "ts": 1 }
    }
])

What I'm trying to do is to draw campBakingTotalDuration trend by its change list number.

**Comment by yinsimei** [comment]
Hi, it turns out to be our server plugin version is not updated.

The problem is fixed now. Thanks.
