### ISSUE TITLE
Please need help: Error Position 204

### ISSUE THREAD

**Issue by nivre** [JamesOsgood/mongodb-grafana#38]
I have this MongoDB Shell Query: But getting "Unexpected token _ in JSON at position 204".

db.events.aggregate([
    { "$match": {
        "$and": [ 
              {"Environment": { "$eq": "Production"}},
              {"TimeStamp": { "$gte": "$from", "$lt": "$to" }}
        ]
    }},
    { "$group": { 
         _id: { ActionResult: "$ActionResult", ClientType: "$ClientType"  },
         cnt: { "$sum": 1 },
         TimeStampValue: { "$max": "$TimeStamp" }
    }},
    { "$project": { "name": { "$concat": [ "$_id.ClientType",  ": " ,  "$_id.ActionResult" ]},  
                  "value": "$cnt", "ts": "$TimeStampValue", _id: 0 }}
])

**Comment by nivre** [comment]
Heres the screenshot:
![image](https://user-images.githubusercontent.com/6865011/51066784-57f42400-15c1-11e9-953b-648fbfded185.png)


Heres the screenshot from MongoDB Shell:
![image](https://user-images.githubusercontent.com/6865011/51066804-83770e80-15c1-11e9-9369-ae8fad0544c7.png)

**Comment by JamesOsgood** [comment]
You need to put _id in quotes = "_id" : 0

James

**Comment by nivre** [comment]
Hi James, it did not work...
Question: Do I have to change all "mongoDB_url" and "mongoDB_db" hardcoded values to my replicaSets in mongodb-grafana-master project?

**Comment by nivre** [comment]
I got it working James.... I just have to fix the malformed JSON MongoDB query.
Thank you very much....
