### ISSUE TITLE
Support for creating alerts

### ISSUE THREAD

**Issue by janvlasaty** [JamesOsgood/mongodb-grafana#39]
Test rule returns
error:"tsdb.HandleRequest() error Could not find executor for data source type: grafana-mongodb-datasource"

**Comment by janvlasaty** [comment]
According to http://docs.grafana.org/alerting/rules/#execution is not possible to implement Alerting for custom datasource.

**Comment by sanderp42** [comment]
I see that this issue is closed. Is it now supported?
