### ISSUE TITLE
Error while installing Mongo Proxy npm install 

### ISSUE THREAD

**Issue by VinodhThiagarajan1309** [JamesOsgood/mongodb-grafana#4]
Thanks a lot for the plugin
`npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-clean@1.1.0 wants grunt@>=0.4.5
npm ERR! peerinvalid Peer grunt-execute@0.2.2 wants grunt@~0.4.1
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.2 wants grunt@>=0.4.0

npm ERR! System Linux 4.9.49-moby
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/lib/grafana/plugins/mongodb-grafana
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/lib/grafana/plugins/mongodb-grafana/npm-debug.log
npm ERR! not ok code 0`

**Comment by ChloeTian** [comment]
Hi, have you fixed this error by any chances? Thanks a lot!
