### ISSUE TITLE
How to auth mongodb.

### ISSUE THREAD

**Issue by Tibingeo** [JamesOsgood/mongodb-grafana#5]
I have a mogo db which requires auth. Is there a way that I can connect to mongo with auth ?

**Comment by mancosun** [comment]
@Tibingeo like this ? "mongodb://username:password@hostname"

**Comment by mancosun** [comment]
@JamesOsgood does mongdb  version > 3.4 is necessary? my mongdb version is 3.2

**Comment by JamesOsgood** [comment]
@mancosun I've only tested against > 3.4 but it's not doing anything clever so will prob work with 3.2.

**Comment by JamesOsgood** [comment]
@Tibingeo Mancosun is correct - just pass the auth in the connection string. The example provided uses Atlas which mandates auth + ssl.

**Comment by Tibingeo** [comment]
Thank You @mancosun got it worked.
