### ISSUE TITLE
proxy error: dial tcp 127.0.0.1:3333: connect: connection refused

### ISSUE THREAD

**Issue by sephiroth6** [JamesOsgood/mongodb-grafana#56]
When I try to add: 

- http-URL = http://localhost:3333

- mongo db url = mongodb://rpiread:rpiread@rpi-sensor-data-shard-00-00-ifxxs.mongodb.net:27017,rpi-sensor-data-shard-00-01-ifxxs.mongodb.net:27017,rpi-sensor-data-shard-00-02-ifxxs.mongodb.net:27017/test?ssl=true&replicaSet=rpi-sensor-data-shard-0&authSource=admin 

I receive this error: proxy error: dial tcp 127.0.0.1:3333: connect: connection refused

I tried with my db: 

- mongodb://xxxxx:xxxx@dsxxxx.mlab.com:00000/xxxxx
or

- mongodb://localhost:27017 

I received same error.

What can I do?
Thank

**Comment by timstallinger** [comment]
How did you solve this?

**Comment by ghost** [comment]
Did you fix the issue? I am erroring out at the MongoDB URL and not sure what to do. Please help. Thanks !
