### ISSUE TITLE
Query not displaying data

### ISSUE THREAD

**Issue by golanudelamare** [JamesOsgood/mongodb-grafana#61]
Hello,

first of all thank you for making possible to link MongoDB to Grafana.

I tried to display some data from my database, connected the database to Grafana correctly but I can't seem to be able to display the data from a collection. Here is my query:

db.endpoint_TEMP_TANK.aggregate( [ 
{  "$match":  {"Timestamp": { "$gte": "2019-06-19T09:54:31.680Z" }}},
{  "$project" :  {"name" : "test", "value" : "$Value", "Timestamp" : "$Timestamp", "_id" : 0  }  }  ]  )

I receive no warnings whatsoever, only Grafana displays "No data points". 

I've also tried to play a little and change the query  "$gte": "ISODate(2019-06-19T09:54:31.680Z)" but then I receive an error.

Here a screenshot of one entry in my collection. They all have the same schema.
![Unbenannt](https://user-images.githubusercontent.com/25983349/59758891-36dde080-928f-11e9-9c1f-b1c7cb9b73da.jpg)

**Comment by golanudelamare** [comment]
If someone is bothered to stumble upon this post, here is my solution:

db.endpoint_TEMP_TANK.aggregate( [ 
{"$match":  {"Timestamp": {"$gte": "$from" , "$lte": "$to" }}},
{"$sort": {"Timestamp": 1}},
{"$project": {"name" : "test", "value" : "$Value", "ts" : "$Timestamp", "_id" : 0  }  }  ])

The $sort is not mandatory.

**Comment by Adhira-Deogade** [comment]
I still can't fetch any data.
