### ISSUE TITLE
error while add data source

### ISSUE THREAD

**Issue by eugsterli** [JamesOsgood/mongodb-grafana#7]
when i try to add the datasource is get the following error:
Fetch error: 404 Not Found Instantiating http://****/public/app/plugins/datasource/grafana-mongodb-datasource/module Loading app/plugins/datasource/grafana-mongodb-datasource/module

**Comment by JamesOsgood** [comment]
Sorry, no idea about that one. Looks like a grafana issue. What version are you running?

**Comment by remusmp** [comment]
I got the same issue. Grafana v5.2.3.

**Comment by Adhira-Deogade** [comment]
Grafana v7.4.3 same error, I am not getting to how to configure it, can I get more details?
