### ISSUE TITLE
 hello，why can I not connect the mongodb？

### ISSUE THREAD

**Issue by yuanyixu** [JamesOsgood/mongodb-grafana#80]
<img width="1046" alt="屏幕快照 2019-12-02 下午7 27 41" src="https://user-images.githubusercontent.com/50541520/70032502-8ff4c300-15e8-11ea-9763-461962eb91dc.png">

**Comment by ghost** [comment]
Hi ! Were you able to fix this issue? What was the Mongo URL you used?

**Comment by boogity** [comment]
For those who run into this issue the relevant settings with basic auth do not need user:password in the mongoDB URL and you should only have the MongoDB URL of your server end at `:port/` The marked over fields above look as follows on my setup and work:

- URL: IP -> this is the IP of the Grafana/MongoDB API proxy you started with `npm server start` (probably localhost)
- User: mongodb user -> Pretty straight forward, if you have auth on your mongoDB then it should be set to the user/password you configured
- MongoDB URL -> `mongodb://mongo_server_ip:27017/` 

Two things stick out to me in the above screenshot: 

1. The user:password may or may not be interfering with the connection (but leaving it there in plaintext, why bother with a password at all then?) but you shouldn't need it.
2. The mongoDB url appears to include at least the database name in the URL, possibly more. Looks like this plugin concatenates all that info (including password/user) for you so leaving it right there in the URL is sure to cause connection issues.
