### ISSUE TITLE
Question - Way to change interval

### ISSUE THREAD

**Issue by itomaldonado** [JamesOsgood/mongodb-grafana#9]
Is there a way to manually change the interval in the body request?

**Comment by JamesOsgood** [comment]
The interval is passed into us from grafana and is based on the date range that is selected in the GUI.

In my aggregations I use the $bucketAuto function to bucket the data up into the appropriate time intervals.

**Comment by itomaldonado** [comment]
So the aggregation and $bucketAuto works wonders for the date ranges, but for example, if I have "last 7 days" but I want to bucket the data into "daily" intervals, I can't do that easily (unless I heavily tweak the $bucketAuto query) since the interval is automatically calculated.

For graphite (and say InfluxDB for example) we can use "interval-type" variables in things like "summarize" that will use the specified interval instead of the default/built-in.

Do you know where I can look at that in your code? I can try to raise a PR to add modifiable intervals, which I think are a great way to display bucket data without doing the heavy lifting in the mongo queries (and allows me to have the intervals as a drop-down variable for easily switching between intervals). 

What do you think? unless you have a better way of tweaking the $bucketAuto to return interval-like summaries for templated/variable intervals.

**Comment by JamesOsgood** [comment]
The problem that I had is that if I pass $bucket with a load of defined buckets, the performance really sucked as MongoDB turns that into a big if-then-else statement whereas $bucketAuto seems to use the index and really flies.....
