### ISSUE TITLE
Help with query

### ISSUE THREAD

**Issue by sohhe** [JamesOsgood/mongodb-grafana#98]
Hello guys. 
I have documents look like:
{"_id{"$oid":"5ede287829e0135b5c8349b1"},
"age":32,
"firstName":"Knowles",
"lastName":"Campos",
"email":"knowlescampos@amril.com"}

I want to show the number of people by age on a diagram. How i can do it? Thanks!

**Comment by Adhira-Deogade** [comment]
How did you resolve this query @sohhe
